### ISSUE TITLE
Xamarin Forms 3.6 breaking changes break pulltorefresh

### ISSUE THREAD

**Issue by raymondjstone** [jamesmontemagno/Xamarin.Forms-PullToRefreshLayout#62]
Not got as far as checking for IOS but can't link android app with pulltorefresh if upgraded to forms 3.6

Other packages report similar issues.

Severity	Code	Description	Project	File	Line	Suppression State
Error		The "LinkAssemblies" task failed unexpectedly.
Mono.Linker.MarkException: Error processing method: 'System.Void Refractored.XamForms.PullToRefresh.Droid.PullToRefreshLayoutRenderer::Xamarin.Forms.Platform.Android.IVisualElementRenderer.add_LayoutChange(System.EventHandler`1<Android.Views.View/LayoutChangeEventArgs>)' in assembly: 'Refractored.XamForms.PullToRefresh.Droid.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve System.Void Xamarin.Forms.Platform.Android.IVisualElementRenderer::add_LayoutChange(System.EventHandler`1<Android.Views.View/LayoutChangeEventArgs>)
   at Mono.Linker.Steps.MarkStep.HandleUnresolvedMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   --- End of inner exception stack trace ---
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
   at Mono.Linker.Steps.MarkStep.Process()
   at MonoDroid.Tuner.MonoDroidMarkStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at MonoDroid.Tuner.Linker.Process(LinkerOptions options, ILogger logger, LinkContext& context)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	MyAberdeenshire.Android	C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets	2129

**Comment by rgwebb** [comment]
Seeing the same issue after upgrading to 3.6. I'm already using a custom class to handle for a disposing bug, any advice on how to workaround this issue?

**Comment by jamesmontemagno** [comment]
Can you try: 2.3.0.40-beta

**Comment by rgwebb** [comment]
I'm not seeing any references to the PullToRefreshLayoutRenderer after installing 2.3.0.40-beta.

**Comment by jamesmontemagno** [comment]
https://www.nuget.org/packages/Refractored.XamForms.PullToRefresh/2.3.0.40-beta

**Comment by jamesmontemagno** [comment]
You must compile against Android 9.0

**Comment by rgwebb** [comment]
Can confirm it works if the project is compiled against Android 9.0.

**Comment by jamesmontemagno** [comment]
2.4.0 will allow 8.1 or 9.0 as the compile target. Lots of changes.

**Comment by MichaelMcKinney** [comment]
Updating to 2.4.1.1 - beta fixed this issue for me once compiling against 9.0. Afterwards I also needed to enable Multi-Dex to successfully build. Thanks for the help everyone!
